baseURL = "https://build.verrazzano.io/docs-stage"
languageCode = "en-us"
title = ""

# Change the default theme to be use when building the site with Hugo
theme = "hugo-book"

publishDir = "publish"

disableKinds = ['taxonomy', 'taxonomyTerm']
enableGitInfo = true

# For search functionality
[outputs]
home = [ "HTML" ]

# Theme configuration
[params]
BookLogo = 'verrazzano-logo.png'
BookRepo = 'https://github.com/verrazzano/docs/'
BookToC  = true